tap "aws/tap"
tap "hashicorp/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "derailed/k9s"

brew "zsh"
brew "unzip"
brew "unbound"
brew "gnutls"
brew "libssh"
# brew "qemu"
brew "aws-cdk"
brew "awscli"
brew "yarn"
brew "aws/tap/aws-sam-cli"
brew "git"
brew "go"
brew "ansible"
brew "checkov"
brew "gcc"
brew "node", link: false
brew "black"
brew "glib"
brew "python@3.9"
brew "p11-kit"
brew "docker"
brew "docker-compose"
brew "lima"
brew "colima"
brew "cpanminus"
brew "curl"
brew "harfbuzz"
brew "libarchive"
brew "libass"
brew "pango"
brew "srt"
brew "tesseract"
brew "freetds"
brew "go"
brew "gobject-introspection"
brew "librsvg"
brew "graphviz"
brew "guile"
brew "hunspell"
brew "infracost"
brew "jq"
brew "krb5"
brew "kubernetes-cli"
brew "libpq"
brew "libproxy"
brew "libressl"
brew "minikube"
brew "derailed/k9s/k9s"
brew "nghttp2"
brew "packer"
brew "php"
brew "poppler"
brew "pyenv"
brew "python@3.10"
brew "tcl-tk"
brew "qt"
brew "streamlink"
brew "telnet"
brew "terraform"
brew "terraform-docs"
brew "tree"
brew "watch"
brew "wget"
brew "xmlstarlet"
brew "node"
brew "pcre"
brew "xclip"

# cask "android-platform-tools"
# cask "aws-vault"
# cask "vagrant"
# cask "virtualbox"
